### ISSUE TITLE
Should StatesTable, EventsTable, ActionsTable be placed in a module?

### ISSUE THREAD

**Issue by oruebel** [rly/ndx-structured-behavior#34]
Currently the StatesTable, EventsTable, ActionsTable are added directly to `/acquistion` in the NWBFile. Since these belong together, should we add a module to group those tables in a group?

**Comment by oruebel** [comment]
@mavaylon1 @rly

**Comment by mavaylon1** [comment]
@oruebel How about a bare bones class that stores these tables (with properties for easy access), similar to how HERD stores the resources tables.

**Comment by rly** [comment]
Fixed in #36
